### ISSUE TITLE
Unexpected response from the database

### ISSUE THREAD

**Issue by ziyunzamy** [swiftceipt/SC-XW1#34]
I was trying to add an receipt from the general receipt list, what it is supposed to return is a success message because the receipt id and folder id is correct, following is the request body:

```
{ url: 'https://tenv-service.swiftceipt.com/folders',
  headers: 
   { Accept: 'application/json',
     'Content-Type': 'application/json' },
  json: true,
  body: 
   { authToken: 'eyJraWQiOiJTV0NULWgxMmFicmU0Y2VwNjlqMG0xMXZram1yZnVoIiwiYWxnIjoiUlMyNTYifQ.eyJpc3MiOiJTV0NUQXBwIiwiYXVkIjoiU1dDVEFwcC1TZXJ2aWNlIiwic3ViIjoiIiwiZXhwIjoxNDU5NzIzMzI1LCJqdGkiOiJRdXNTWXNlNFY4ZHBMYks1akUwWFd3IiwiaWF0IjoxNDU5NzIzMjA1LCJuYmYiOjE0NTk3MjMwODUsImVtYWlsIjoiamFja0BjaXJuby5kZSJ9.CkYO0oTl_CcDRVRHWfUr1T2xkMJ1clw4EtX-ctQ-Cd2o6vOBX-oXScMxBmFpptArRpcLBISNW3NXewSsNR6Ng8ZnwklRX-UQTUUCx9mWeV3VGqXIdzZraAqv3w0X05_1Vv-xU-ALMwrhDMWaqdheSyhVHD4mSw-NUQgzmsA1fmNi_SW3e5_U-JC76SXaf_NZk2gLNdlObo7qzm3oduhQqkf5cVXsUylJZPIPqCNx6IX_VCsvOIpLBai1FqLcLhYe0Cg6gpZlJmx5f3XVMmDFC5q9Adp6Hp_rzKPR_CkI_HsJh3Gl96DxDzX5EMzcTtghQbnsk06w0OKZQeCP8Zzrmg',
     action: 'PLACE',
     folderName: 'food',
     receiptId: 832 } }

```
However, instead of the success message I should be getting, I got this error message:

```
[ { errorCode: 'ILLEGAL_ARGUMENTS',
    errorId: 9,
    errorMessage: 'You do not own a receipt with this ID.' } ]
```

This usually occurs when I try to perform the adding receipts actions many times in a short time span.

**Comment by SivanMehta** [comment]
Additionally, I am seeing this error consistently when adding 3 receipts to any folder, the 3rd attempt almost always crashes. This implementation can be demonstrated on the `drag_and_drop` branch

**Comment by SivanMehta** [comment]
@kchau101 resolved that there was a memory leak happening which was slowing down our connection,
